[profile.coverage]
inherits = "dev"
codegen-units = 1
incremental = false
opt-level = 0
overflow-checks = false
panic = "abort"

[alias]
####################################################################################################
# core crates

core-flow = """
watch --clear
    -w dyn-cache
    -w illicit
    -w mox
    -w src
    -w topo
    -w Cargo.toml
    -x clippy-core
    -x test-core
    -x test-core-doc
"""

clippy-core = """clippy
--package dyn-cache
--package illicit
--package illicit-macro
--package mox
--package moxie
--package topo
--package topo-macro
"""
test-core = """test --all-targets
--package dyn-cache
--package illicit
--package illicit-macro
--package mox
--package moxie
--package topo
--package topo-macro
"""
test-core-doc = """test --doc
--package dyn-cache
--package illicit
--package illicit-macro
--package mox
--package moxie
--package topo
--package topo-macro
"""

docs-all = "doc --workspace --no-deps --all-features"

build-times = "build --workspace --all-targets --all-features -Z timings"

####################################################################################################
# dom crates and examples

dom-flow = """
watch --clear
    -x build-dom-todo
    -x build-dom-hacking
    -x test-prettiest
    -x test-dom
    -x test-dom-doc
    -x test-augdom
    -x test-dom-todo
    -x test-dom-lib-browser
    -x test-dom-drivertest
    -x test-dom-hacking
    -x clippy-dom
"""

wa-pack = "run --manifest-path dom/local-wasm-pack/Cargo.toml --"
wa-pack-build = "wa-pack build --target web --out-name index"
wa-test = "wa-pack test --chrome --headless"

build-dom-lib = "wa-pack-build dom"
build-dom-hacking = "wa-pack-build dom/examples/hacking"
build-dom-todo = "wa-pack-build dom/examples/todo"

# browser tests
test-augdom = "wa-test dom/augdom"
test-prettiest = "wa-test dom/prettiest"
test-dom-lib-browser = "wa-test dom"
test-dom-drivertest = "wa-test dom/examples/drivertest"
test-dom-hacking = "wa-test dom/examples/hacking"
test-dom-todo = "wa-test dom/examples/todo"
test-dom-todo-e2e = """
ofl serve-then-run 
    --cargo-before build-dom-todo 
    --cwd dom/examples/todo/e2e -- 
npx cypress run
"""

# standalones
test-dom = "test --package moxie-dom --package ssr-poc --all-targets"
test-dom-doc = "test --package moxie-dom --package ssr-poc --doc"

# dom utilities
clippy-dom = """clippy
    --all-targets
    --all-features
    --package moxie-dom
    --package dom-hacking
    --package todomvc-moxie
"""

####################################################################################################
# ofl

ofl = "run --manifest-path ofl/Cargo.toml --release --"
server = "watch -w ofl/ -x ofl"

ofl-flow = """
watch --clear -w ofl
    -x clippy-ofl
    -x test-ofl
    -x docs-ofl
"""
site-flow = "watch --clear -x ofl-build-website"


ofl-build-website = "ofl website build target/website"
ofl-fmt-project = "ofl fmt"
clippy-ofl = "clippy --manifest-path ofl/Cargo.toml --workspace"
test-ofl = "test --manifest-path ofl/Cargo.toml --workspace"
docs-ofl = "doc --manifest-path ofl/Cargo.toml --workspace --no-deps"
