[package]
name = "ssr-poc"
version = "0.1.0"
publish = false
authors = ["Adam Perry <lol@anp.lol>"]
edition = "2018"
description = "proof of concept for server-side rendered HTML with moxie-dom"

[dependencies]
augdom = { path = "../../augdom" }
gotham = "0.6.0"
gotham_derive = "0.6.0"
hyper = "0.14"
mox = { path = "../../../mox" }
moxie = { path = "../../../" }
serde = "1"
serde_derive = "1"
topo = { path = "../../../topo" }

[dependencies.moxie-dom]
path = "../../"
default-features = false
features = [ "rsdom" ]