[package]
name = "dom-hacking"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0/MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_log = "0.1"
log = "0.4"
moxie = { path = "../../../../" }
moxie-dom = { path = "../../../" }
stdweb = "0.4.16"
wasm-bindgen = "0.2"
