[package]
name = "topo"
version = "0.8.2-pre"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Reified activation records and scoped thread-locals for UI runtimes."
repository = "https://github.com/anp/moxie"

include = ["Cargo.toml", "src/**/*.rs", "benches/**/*.rs", "tests/**/*.rs"]

[dependencies]
owning_ref = "0.4"
scopeguard = "1"
topo-macro = { path = "macro", version = "=0.8.1" }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "simple"
harness = false
